import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// JavaScript build options
const jsBuildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  alias: {
    react: "preact/compat",
    "react-dom": "preact/compat",
    "react-dom/client": "preact/compat/client",
    "react/jsx-runtime": "preact/jsx-runtime",
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
  minify: prod,
  metafile: true,
  drop: prod ? ["console", "debugger"] : [],
};

// SCSS build options
const cssBuildOptions = {
  entryPoints: ["./src/styles/main.scss"],
  bundle: true,
  plugins: [sassPlugin()],
  outfile: "styles.css",
  logLevel: "info",
  minify: prod,
};

function analyzeMetafile(metafile) {
  const inputs = Object.entries(metafile.inputs)
    .map(([path, data]) => ({ path, bytes: data.bytes }))
    .sort((a, b) => b.bytes - a.bytes);

  const total = inputs.reduce((sum, f) => sum + f.bytes, 0);
  const output = Object.values(metafile.outputs)[0];

  console.log("\n📦 Bundle Analysis");
  console.log("─".repeat(60));
  console.log(`Output size: ${(output.bytes / 1024).toFixed(1)} KB`);
  console.log(`Total input: ${(total / 1024).toFixed(1)} KB`);
  console.log("\nTop 15 largest inputs:");
  console.log("─".repeat(60));

  inputs.slice(0, 15).forEach((f, i) => {
    const kb = (f.bytes / 1024).toFixed(1).padStart(7);
    const pct = ((f.bytes / total) * 100).toFixed(1).padStart(5);
    const name = f.path.replace("node_modules/", "nm/");
    console.log(`${(i + 1).toString().padStart(2)}. ${kb} KB (${pct}%)  ${name}`);
  });

  fs.writeFileSync("meta.json", JSON.stringify(metafile, null, 2));
  console.log("\nFull metafile written to meta.json");
  console.log("View at: https://esbuild.github.io/analyze/\n");
}

if (prod) {
  const [jsResult] = await Promise.all([
    esbuild.build(jsBuildOptions),
    esbuild.build(cssBuildOptions),
  ]);
  analyzeMetafile(jsResult.metafile);
} else {
  const [jsCtx, cssCtx] = await Promise.all([
    esbuild.context(jsBuildOptions),
    esbuild.context(cssBuildOptions),
  ]);
  await Promise.all([jsCtx.watch(), cssCtx.watch()]);
}
