import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// JavaScript build options
const jsBuildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
  minify: prod,
};

// SCSS build options
const cssBuildOptions = {
  entryPoints: ["./src/styles/main.scss"],
  bundle: true,
  plugins: [sassPlugin()],
  outfile: "styles.css",
  logLevel: "info",
  minify: prod,
};

if (prod) {
  await Promise.all([
    esbuild.build(jsBuildOptions),
    esbuild.build(cssBuildOptions),
  ]);
} else {
  const [jsCtx, cssCtx] = await Promise.all([
    esbuild.context(jsBuildOptions),
    esbuild.context(cssBuildOptions),
  ]);
  await Promise.all([jsCtx.watch(), cssCtx.watch()]);
}
